package Modelo;
// Generated 30/08/2018 13:37:47 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private String apellido;
     private int dni;
     private String domicilio;
     private Integer nro;
     private Integer piso;
     private String dto;
     private String ciudad;
     private Integer codArea;
     private Integer celular;

    public Usuario() {
    }

	
    public Usuario(int dni) {
        this.dni = dni;
    }
    public Usuario(String nombre, String apellido, int dni, String domicilio, Integer nro, Integer piso, String dto, String ciudad, Integer codArea, Integer celular) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.domicilio = domicilio;
       this.nro = nro;
       this.piso = piso;
       this.dto = dto;
       this.ciudad = ciudad;
       this.codArea = codArea;
       this.celular = celular;
    }

    public Usuario(String text, String text0, String text1, int parseInt, int parseInt0, String text2, int parseInt1, int parseInt2, int parseInt3) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public Integer getNro() {
        return this.nro;
    }
    
    public void setNro(Integer nro) {
        this.nro = nro;
    }
    public Integer getPiso() {
        return this.piso;
    }
    
    public void setPiso(Integer piso) {
        this.piso = piso;
    }
    public String getDto() {
        return this.dto;
    }
    
    public void setDto(String dto) {
        this.dto = dto;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Integer getCodArea() {
        return this.codArea;
    }
    
    public void setCodArea(Integer codArea) {
        this.codArea = codArea;
    }
    public Integer getCelular() {
        return this.celular;
    }
    
    public void setCelular(Integer celular) {
        this.celular = celular;
    }

    public void setidUsuario(int i) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


